apiVersion: 1

datasources:
  - name: MySQL
    type: mysql
    url: mysql:3306
    database: database
    user: root
    secureJsonData:
      password: rootpassword
    jsonData:
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
    isDefault: true
    editable: true