
metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "lmdb"

[rpc]
rpc_secret = "myrpcsecret456"

[s3_api]
bind_addr = "0.0.0.0:3900"
s3_region = "dev"

[admin]
bind_addr = "0.0.0.0:3903"
admin_token = "mon-token-admin-secret"