receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
  groupbyattrs:
    keys: []

exporters:
  otlphttp:
    endpoint: "http://loki:3100/otlp"
  # prometheus:
  #   endpoint: "0.0.0.0:8889"
  # otlp/tempo:
  debug:
    verbosity: detailed
service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp, debug]
    # metrics:
    # receivers: [otlp]
    # processors: [cumulativetodelta]
    # exporters: [prometheus]
    # metrics:
    #  receivers: [otlp]
    #  processors: [groupbyattrs, batch]
    #  exporters: [debug, prometheus]
    # traces:
    #  receivers: [otlp]
    #  processors: [batch]
    #  exporters: [otlp/tempo]