receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  otlp_http/loki:
    endpoint: "http://loki:3100/otlp"
  prometheus:
    endpoint: "0.0.0.0:8889"
  otlp/tempo:
    endpoint: "tempo:3200"
  debug:
    verbosity: detailed
service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp_http/loki]
    metrics:
      receivers: [otlp]
      processors: [groupbyattrs, batch]
      exporters: [prometheus]
    # metrics:
    # receivers: [otlp]
    # processors: [cumulativetodelta]
    # exporters: [prometheus]

    # traces:
    #  receivers: [otlp]
    #  processors: [batch]
    #  exporters: [otlp/tempo]