receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:
  groupbyattrs:
    keys: []

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
  otlp/logs:
    endpoint: "http://loki:3100/otlp"
  otlp/tempo:
  debug:
    verbosity: detailed

service:
  pipelines:
    # metrics:
    # receivers: [otlp]
    # processors: [cumulativetodelta]
    # exporters: [prometheus]
    # metrics:
    #  receivers: [otlp]
    #  processors: [groupbyattrs, batch]
    #  exporters: [debug, prometheus]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/logs, debug]
    # traces:
    #  receivers: [otlp]
    #  processors: [batch]
    #  exporters: [otlp/tempo]